### ISSUE TITLE
GUNW layer inconsistencies between 

### ISSUE THREAD

**Issue by sssangha** [isce-framework/nisar-workflows#15]
Hello, to whom it may concern we have been looking at NISAR beta GUNW sample products we've received from ADT vs those we've accessed through asf vertex.

We've noticed some discrepancies in the embedded layers.

Specifically, the sample products we received from ADT do not have the following layers:
`/science/LSAR/GUNW/metadata/attitude/angularVelocity`, `/science/LSAR/GUNW/metadata/orbit/acceleration`

But it does have the following layers that a sample product from asf vertex (e.g. NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20080415T033910_20080415T033923_20100410T062229_20100410T062243_T00888_M_F_J_888.h5) does not have:
`/science/LSAR/GUNW/metadata/radarGrid/hydrostaticTroposphericPhaseScreen` and `/science/LSAR/GUNW/metadata/radarGrid/wetTroposphericPhaseScreen`.

Also, upon closer inspection, the products available through asf vertex themselves aren't internally consistent with eachother.

For reference, here are all of the products that I have accessed through asf_vertex:
```
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20080415T033910_20080415T033923_20100410T062229_20100410T062243_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20100317T063157_20100317T063211_20110202T062738_20110202T062752_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20100317T063157_20100317T063211_20110320T062633_20110320T062646_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20110202T062738_20110202T062752_20110320T062633_20110320T062646_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20230728T105822_20230728T105832_20230811T105822_20230811T105832_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20230811T105742_20230811T105752_20230825T105742_20230825T105752_T00888_M_F_J_888.h5
NISAR_L2_PR_GUNW_034_080_A_010_035_2005_SV_20230619T000803_20230619T000835_20230701T000803_20230701T000835_P00401_M_P_J_001.h5
NISAR_L2_PR_GUNW_035_080_A_010_036_2005_SV_20230701T000803_20230701T000835_20230713T000803_20230713T000835_P00401_M_P_J_001.h5
NISAR_L2_PR_GUNW_035_080_A_010_036_2005_SV_20230701T000803_20230701T000835_20230713T000803_20230713T000835_P00401_M_P_J_996.h5
```

Only `NISAR_L2_PR_GUNW_035_080_A_010_036_2005_SV_20230701T000803_20230701T000835_20230713T000803_20230713T000835_P00401_M_P_J_996.h5, NISAR_L2_PR_GUNW_035_080_A_010_036_2005_SV_20230701T000803_20230701T000835_20230713T000803_20230713T000835_P00401_M_P_J_001.h5, NISAR_L2_PR_GUNW_034_080_A_010_035_2005_SV_20230619T000803_20230619T000835_20230701T000803_20230701T000835_P00401_M_P_J_001.h5` have these layers: `/science/LSAR/GUNW/metadata/radarGrid/hydrostaticTroposphericPhaseScreen` and `/science/LSAR/GUNW/metadata/radarGrid/wetTroposphericPhaseScreen` and `/science/LSAR/GUNW/grids/frequencyA/unwrappedInterferogram/mask`.

And within the `NISAR_L2_PR_GUNW_001_001_A_150_013_2000_SH_20100317T063157_20100317T063211_20110202T062738_20110202T062752_T00888_M_F_J_888.h5` product, the layer name `slantRangeSolidEarthTidesPhase` has been changed to `losSolidEarthTidesPhase` relative to other products

Please advise on what the appropriate reference product would be, which would help inform ongoing developments to the [ARIA-tools](https://github.com/aria-tools/ARIA-tools) software that are intended to provide support to access and manage NISAR beta GUNW products.

Many thanks!

**Comment by hfattahi** [comment]
Thanks @sssangha for your feedbacks. The first set of products on vertex were not meant to be evaluated against spec. They could have been produced with different developer versions of the software at different stages. We just released the new sample products and product specs to the DAAC which are available on the [nisar website](https://nisar.jpl.nasa.gov/data/sample-data/). These are the latest and greatest sample products and spec documents released. Please rely on them for your developments. Let me know if this addresses your questions. The spec dates May 30 2024 and the product specification version is 1.1.0.

**Comment by dbekaert** [comment]
@sssangha please try the new products. Closing this here for the time being.
