### ISSUE TITLE
Issue with GOFF and NASA's HDF viewer panoply

### ISSUE THREAD

**Issue by alex-s-gardner** [isce-framework/nisar-workflows#6]
It seems that all products EXCEPT GOFF (created by @vbrancat ) can be opened by NASA's Panoply HDF viewer:
https://www.giss.nasa.gov/tools/panoply/download/

When I try to open the GOFF product I get this error:
<img width="514" alt="Screenshot 2024-02-12 at 3 08 05 PM" src="https://github.com/isce-framework/nisar-workflows/assets/32276930/bf88ff0c-f308-4ac0-a99f-9fcf07cdfa9a">

**Comment by bscheuchl** [comment]
Checked with the revised version (issued 3/12) and this seems to work now

**Comment by vbrancat** [comment]
Hi @alex-s-gardner, this issue has been solver in our [ISCE3 v0.21.0](https://github.com/isce-framework/isce3/releases/tag/v0.21.0) release. See attached screenshot showing a slant range Offset layer from our latest NISAR sample products opened in panoply. 

![Screenshot 2024-08-02 at 4 33 48 PM](https://github.com/user-attachments/assets/bd6352cf-c371-4c71-8220-43ef78cf9781)
